Get links for e2e
OsomePteLtd/actions pull request #34
Opened 2020-12-13 10:38 UTC by vponomarev279

2020-12-13 10:39 UTC, vponomarev279 commented
Action который отдает три ссылки: websome, agent и backend. Дальше эти ссылки подставляем в энвики e2e

2020-12-13 22:18 UTC, AlekseyLeshko requested changes

2020-12-13 22:18 UTC, AlekseyLeshko commented on packages/get-stages-for-e2e/src/index.ts
> +    return 'https://api.stage.osome.club/api/v2';
Можно использовать `defaultUrls`
и ниже еще 2 штуки такие же

2020-12-13 22:18 UTC, AlekseyLeshko commented on packages/get-stages-for-e2e/package.json
> +  "author": "Vlad Ponomarev <v.ponomarev@osome.com>",
"author": "Osome Pte. Ltd." 😉

2020-12-13 22:18 UTC, AlekseyLeshko commented on packages/get-stages-for-e2e/package.json
> +  "license": "UNLICENSED",
С лицензиями у нас все как-то непонятно. Надо будет подумать, почитать

2020-12-14 09:22 UTC, heuels approved these changes
Может, назвать `get-e2e-stages`?

2020-12-14 16:01 UTC, vponomarev279 commented on packages/get-stages-for-e2e/src/index.ts
> +    return 'https://api.stage.osome.club/api/v2';
Точно!

2020-12-14 16:03 UTC, vponomarev279 commented on packages/get-stages-for-e2e/package.json
> +  "author": "Vlad Ponomarev <v.ponomarev@osome.com>",
Ну чейта! Почта то корпоративная) ну и посмотри остальные экшены, там указаны авторы. Единообразие ✌️

2020-12-14 16:04 UTC, vponomarev279 commented on packages/get-stages-for-e2e/package.json
> +  "license": "UNLICENSED",
Ага. Это я скопировал из соседних экшенов

2020-12-14 20:25 UTC, AlekseyLeshko commented on packages/get-stages-for-e2e/package.json
> +  "author": "Vlad Ponomarev <v.ponomarev@osome.com>",
Все принадлежит `Osome`
Рука пройдется поправит везде ✋

2020-12-15 08:22 UTC, vponomarev279 commented on packages/get-stages-for-e2e/package.json
> +  "author": "Vlad Ponomarev <v.ponomarev@osome.com>",
Сделал

2020-12-15 08:22 UTC, vponomarev279 commented
> Может, назвать `get-e2e-stages`?

Согласен, так лучше. Переименовал

2020-12-15 08:24 UTC, vponomarev279 commented on packages/get-stages-for-e2e/src/index.ts
> +    return 'https://api.stage.osome.club/api/v2';
done

2020-12-15 12:19 UTC, AlekseyLeshko approved these changes

2020-12-15 17:40 UTC, merged